# Generated by Django 4.1.10 on 2023-07-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(blank=True, choices=[('EMPRESA', 'Empresa'), ('ESPECIFICADOR', 'Especificador')], max_length=20, null=True),
        ),
    ]
